pub(super) const SCHEMA: &[&str] = &[
    r#"
    CREATE TABLE IF NOT EXISTS backtest_results (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      strategy_name TEXT NOT NULL,
      strategy_id TEXT NOT NULL,
      symbol TEXT NOT NULL,
      inst_type TEXT NOT NULL DEFAULT 'SPOT',
      timeframe TEXT NOT NULL,
      days INTEGER NOT NULL,
      start_time TEXT,
      end_time TEXT,
      initial_capital REAL NOT NULL,
      final_capital REAL NOT NULL,
      total_return REAL,
      annual_return REAL,
      max_drawdown REAL,
      sharpe_ratio REAL,
      sortino_ratio REAL,
      calmar_ratio REAL,
      win_rate REAL,
      profit_factor REAL,
      total_trades INTEGER,
      winning_trades INTEGER,
      losing_trades INTEGER,
      avg_profit REAL,
      avg_loss REAL,
      largest_profit REAL,
      largest_loss REAL,
      total_commission REAL,
      params_json TEXT,
      detail_json TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    "#,
    "CREATE INDEX IF NOT EXISTS idx_backtest_strategy ON backtest_results(strategy_id, symbol)",
    "CREATE INDEX IF NOT EXISTS idx_backtest_time ON backtest_results(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_backtest_strategy_recent ON backtest_results(strategy_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_backtest_strategy_symbol_recent ON backtest_results(strategy_id, symbol, created_at DESC)",
];
