pub(super) const SCHEMA: &[&str] = &[
    r#"
    CREATE TABLE IF NOT EXISTS local_fills (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      trade_id TEXT,
      inst_id TEXT NOT NULL,
      ccy TEXT NOT NULL,
      side TEXT NOT NULL,
      fill_px TEXT NOT NULL,
      fill_sz TEXT NOT NULL,
      fee TEXT DEFAULT '0',
      fee_ccy TEXT,
      ts INTEGER NOT NULL,
      mode TEXT NOT NULL,
      source TEXT DEFAULT 'api',
      order_id TEXT DEFAULT '',
      client_order_id TEXT DEFAULT '',
      strategy_id TEXT DEFAULT '',
      run_id TEXT DEFAULT '',
      arrival_ts INTEGER,
      arrival_mid_px REAL,
      arrival_bid_px REAL,
      arrival_ask_px REAL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(trade_id, mode)
    )
    "#,
    "CREATE INDEX IF NOT EXISTS idx_fills_ccy_mode ON local_fills(ccy, mode)",
    "CREATE INDEX IF NOT EXISTS idx_fills_ts ON local_fills(ts)",
    "CREATE INDEX IF NOT EXISTS idx_fills_mode_ts ON local_fills(mode, ts DESC)",
    "CREATE INDEX IF NOT EXISTS idx_fills_mode_inst_ts ON local_fills(mode, inst_id, ts DESC)",
    r#"
    CREATE TABLE IF NOT EXISTS cost_basis (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      ccy TEXT NOT NULL,
      mode TEXT NOT NULL,
      avg_cost TEXT NOT NULL,
      total_qty TEXT NOT NULL,
      total_cost TEXT NOT NULL,
      total_fee TEXT NOT NULL DEFAULT '0',
      total_buy_cost TEXT NOT NULL DEFAULT '0',
      total_sell_revenue TEXT NOT NULL DEFAULT '0',
      last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(ccy, mode)
    )
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS okx_account_fee_rates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      mode TEXT NOT NULL,
      inst_type TEXT NOT NULL,
      inst_id TEXT NOT NULL DEFAULT '',
      inst_family TEXT NOT NULL DEFAULT '',
      maker_rate REAL,
      taker_rate REAL,
      maker_u_rate REAL,
      taker_u_rate REAL,
      maker_usdc_rate REAL,
      taker_usdc_rate REAL,
      level TEXT NOT NULL DEFAULT '',
      payload_json TEXT NOT NULL DEFAULT '{}',
      fetched_at INTEGER NOT NULL,
      source TEXT NOT NULL DEFAULT 'okx_account_trade_fee',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(mode, inst_type, inst_id, inst_family)
    )
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS live_order_records (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      strategy_id TEXT NOT NULL,
      strategy_name TEXT NOT NULL,
      symbol TEXT NOT NULL,
      inst_id TEXT NOT NULL DEFAULT '',
      inst_type TEXT NOT NULL DEFAULT '',
      side TEXT NOT NULL,
      order_type TEXT NOT NULL,
      size REAL NOT NULL,
      price REAL,
      order_id TEXT,
      client_order_id TEXT DEFAULT '',
      parent_order_id TEXT DEFAULT '',
      parent_client_order_id TEXT DEFAULT '',
      actual_order_id TEXT DEFAULT '',
      actual_client_order_id TEXT DEFAULT '',
      status TEXT NOT NULL,
      action TEXT,
      error_message TEXT,
      mode TEXT NOT NULL DEFAULT 'simulated',
      success INTEGER NOT NULL DEFAULT 0,
      run_id TEXT DEFAULT '',
      action_timestamp INTEGER,
      arrival_ts INTEGER,
      arrival_mid_px REAL,
      arrival_bid_px REAL,
      arrival_ask_px REAL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS live_execution_plans (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      plan_key TEXT NOT NULL UNIQUE,
      strategy_id TEXT NOT NULL,
      strategy_name TEXT NOT NULL,
      mode TEXT NOT NULL DEFAULT 'simulated',
      entry_run_id TEXT NOT NULL DEFAULT '',
      exit_run_id TEXT NOT NULL DEFAULT '',
      symbol TEXT NOT NULL,
      inst_id TEXT NOT NULL DEFAULT '',
      inst_type TEXT NOT NULL DEFAULT '',
      timeframe TEXT NOT NULL DEFAULT '',
      entry_order_id TEXT NOT NULL DEFAULT '',
      entry_client_order_id TEXT NOT NULL DEFAULT '',
      entry_action_timestamp INTEGER NOT NULL DEFAULT 0,
      entry_side TEXT NOT NULL DEFAULT '',
      entry_price REAL,
      close_side TEXT NOT NULL DEFAULT '',
      planned_exit_time INTEGER NOT NULL,
      planned_exit_reason TEXT NOT NULL DEFAULT 'planned_exit',
      planned_exit_contract TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'scheduled',
      exit_order_id TEXT NOT NULL DEFAULT '',
      exit_client_order_id TEXT NOT NULL DEFAULT '',
      exit_order_history TEXT NOT NULL DEFAULT '',
      attempt_count INTEGER NOT NULL DEFAULT 0,
      next_attempt_at INTEGER NOT NULL DEFAULT 0,
      last_error TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    "#,
    r#"
    CREATE TABLE IF NOT EXISTS live_execution_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      run_id TEXT NOT NULL,
      mode TEXT NOT NULL DEFAULT '',
      strategy_id TEXT NOT NULL DEFAULT '',
      strategy_name TEXT NOT NULL DEFAULT '',
      symbol TEXT NOT NULL DEFAULT '',
      inst_type TEXT NOT NULL DEFAULT '',
      timeframe TEXT NOT NULL DEFAULT '',
      seq INTEGER NOT NULL,
      timestamp_ms INTEGER NOT NULL,
      time TEXT NOT NULL DEFAULT '',
      stage TEXT NOT NULL DEFAULT '',
      level TEXT NOT NULL DEFAULT 'info',
      message TEXT NOT NULL DEFAULT '',
      details_json TEXT NOT NULL DEFAULT '{}',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    "#,
    "CREATE INDEX IF NOT EXISTS idx_live_orders_time ON live_order_records(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_strategy ON live_order_records(strategy_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode ON live_order_records(mode)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_recent ON live_order_records(mode, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_client_id ON live_order_records(client_order_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_order_recent ON live_order_records(mode, order_id, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_client_recent ON live_order_records(mode, client_order_id, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_due ON live_execution_plans(mode, strategy_id, status, planned_exit_time, next_attempt_at)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_entry_run ON live_execution_plans(entry_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_exit_run ON live_execution_plans(exit_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_run_recent ON live_execution_logs(run_id, timestamp_ms DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_recent ON live_execution_logs(timestamp_ms DESC, id DESC)",
    r#"
    CREATE TABLE IF NOT EXISTS portfolio_snapshots (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      mode TEXT NOT NULL,
      date TEXT NOT NULL,
      total_equity REAL NOT NULL,
      spot_value REAL DEFAULT 0,
      contract_value REAL DEFAULT 0,
      cash_value REAL DEFAULT 0,
      positions_json TEXT DEFAULT '{}',
      metadata_json TEXT DEFAULT '{}',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(mode, date)
    )
    "#,
    "CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_mode_date ON portfolio_snapshots(mode, date)",
];

pub(super) const POST_MIGRATION_SCHEMA: &[&str] = &[
    "CREATE INDEX IF NOT EXISTS idx_fills_order_id ON local_fills(order_id)",
    "CREATE INDEX IF NOT EXISTS idx_fills_client_order_id ON local_fills(client_order_id)",
    "CREATE INDEX IF NOT EXISTS idx_fills_strategy_run ON local_fills(strategy_id, run_id)",
    "CREATE INDEX IF NOT EXISTS idx_okx_account_fee_rates_scope ON okx_account_fee_rates(mode, inst_type, inst_id, inst_family)",
    "CREATE INDEX IF NOT EXISTS idx_okx_account_fee_rates_fetched_at ON okx_account_fee_rates(fetched_at)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_run ON live_order_records(run_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_run_recent ON live_order_records(mode, run_id, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_parent_order_recent ON live_order_records(mode, parent_order_id, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_mode_parent_client_recent ON live_order_records(mode, parent_client_order_id, created_at DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_action_ts ON live_order_records(action_timestamp)",
    "CREATE INDEX IF NOT EXISTS idx_live_orders_arrival_ts ON live_order_records(arrival_ts)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_due ON live_execution_plans(mode, strategy_id, status, planned_exit_time, next_attempt_at)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_entry_run ON live_execution_plans(entry_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_plans_exit_run ON live_execution_plans(exit_run_id)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_run_recent ON live_execution_logs(run_id, timestamp_ms DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_mode_run_recent ON live_execution_logs(mode, run_id, timestamp_ms DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_mode_recent ON live_execution_logs(mode, timestamp_ms DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS idx_live_execution_logs_recent ON live_execution_logs(timestamp_ms DESC, id DESC)",
];
