export const paramLabels: Record<string, string> = {
  initial_capital: '初始资金',
  execution_model: '执行模型',
  cost_model: '费用模型',
  params_used_by_engine: '引擎使用的原始参数',
  signal_execution: '动作执行',
  timing: '执行时机',
  delay_bars: '执行延迟K线数',
  price: '成交价格来源',
  contract_mode: '合约模式',
  fee_rate: '手续费率',
  commission_rate: '佣金/手续费率',
  slippage_rate: '滑点率',
  funding_rate_8h: '资金费率/8小时',
  total_funding: '累计资金费',
  leverage: '杠杆倍数',
  td_mode: '保证金模式',
  mgn_mode: '保证金模式',
  margin_mode: '保证金模式',
  position_size: '仓位大小',
  position_size_mode: '仓位大小模式',
  position_sizing: '仓位计算方式',
  position_size_is_notional: '仓位按名义价值计算',
  position_size_is_effective_notional: '仓位按有效名义价值计算',
  allow_short: '允许做空',
  max_hold_bars: '最大持仓K线数',
  maintenance_margin_rate: '维持保证金率',
  execution_timing: '执行时机',
  execution_delay_bars: '执行延迟K线数',
  execution_price: '成交价格来源',
  stop_loss: '止损比例',
  take_profit: '止盈比例',
  max_single_loss_ratio: '单笔最大亏损比例',
  max_symbol_exposure_pct: '单标的最大暴露比例',
  max_position_pct: '最大持仓比例',
  max_order_value: '最大下单金额',
  require_stop_loss: '要求止损',
  risk_control_enabled: '启用风险控制',
  max_leverage: '最大杠杆',
  max_daily_loss_ratio: '每日最大亏损比例',
  max_same_direction_exposure_pct: '同向最大暴露比例',
  strict_context_gating: '严格上下文门控',
}

export const keyTokenLabels: Record<string, string> = {
  allow: '允许',
  bars: 'K线数',
  candidate: '候选',
  capital: '资金',
  close: '收盘',
  confidence: '置信度',
  context: '上下文',
  contract: '合约',
  control: '控制',
  daily: '每日',
  delay: '延迟',
  direction: '方向',
  enabled: '启用',
  execution: '执行',
  exposure: '暴露',
  fee: '手续费',
  funding: '资金费',
  gating: '门控',
  hold: '持仓',
  initial: '初始',
  leverage: '杠杆',
  loss: '亏损',
  maintenance: '维持',
  margin: '保证金',
  max: '最大',
  min: '最小',
  mode: '模式',
  model: '模型',
  notional: '名义价值',
  open: '开盘',
  order: '订单',
  pct: '比例',
  position: '仓位',
  price: '价格',
  profit: '盈利',
  rate: '率',
  ratio: '比例',
  risk: '风险',
  same: '同向',
  short: '做空',
  single: '单笔',
  size: '大小',
  slippage: '滑点',
  stop: '止损',
  strict: '严格',
  symbol: '标的',
  take: '止盈',
  target: '目标',
  timing: '时机',
  value: '金额',
}

export const enumValueLabels: Record<string, string> = {
  delayed_close: '延迟后按收盘价成交',
  delayed_open: '延迟后按开盘价成交',
  close: '收盘价',
  margin_fraction: '按保证金比例',
  cross: '全仓',
  isolated: '逐仓',
  next_close: '下一根K线收盘成交',
  next_open: '下一根K线开盘成交',
  notional_fraction: '按名义价值比例',
  open: '开盘价',
  same_close: '当前K线收盘成交',
}

export const warningLabels: Record<string, string> = {
  open_actions_missing_planned_exit: '开仓动作缺少计划退出',
  planned_exits_closed_at_end_of_backtest: '部分计划退出未按计划成交',
  positions_closed_at_end_of_backtest: '存在回测结束强平',
  positions_closed_with_last_known_mark: '存在缺行情按最后已知价格强平',
  open_trades_without_close_events: '存在未平仓事件',
  open_positions_missing_mark_price: '未平仓持仓缺少历史标记价',
  all_closes_deferred_to_backtest_end_without_planned_exits: '所有平仓都推迟到回测结束且缺计划退出',
  open_actions_skipped_existing_position: '部分开仓因已有同向持仓被忽略',
}

export const integrityIssueLabels: Record<string, string> = {
  runtime_action_summary_missing: '缺少运行时摘要',
  runtime_action_summary_warnings: '运行时摘要存在告警',
  runtime_open_actions_missing_planned_exit: '开仓动作缺少计划退出',
  runtime_closes_without_planned_lifecycle: '平仓只来自止盈止损或回测结束',
  planned_exit_missing: '缺少计划退出',
  planned_exit_partial: '计划退出部分缺失',
  strategy_history_planned_exit_missing: '策略历史动作缺少计划退出',
  strategy_history_planned_exit_partial: '策略历史动作计划退出部分缺失',
  strategy_runtime_action_contract_mismatch: '策略动作合同与执行摘要不一致',
  ...warningLabels,
}

export const plannedExitContractLabels: Record<string, string> = {
  no_open_actions: '无开仓动作',
  planned_exit_complete: '计划退出完整',
  planned_exit_partial: '计划退出部分缺失',
  planned_exit_missing: '缺少计划退出',
}
